# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

title: Thoughts
tagline: ""
email: me@cyriacthomas.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cyriacthomas.com" # the base hostname & protocol for your site
name: Cyriac Thomas

twitter_username: cyriacthomas
github_username:  cyriac
medium_username: cyriacthomas
google_plus_username: CyriacThomas
linkedin_username: cyriacthomas

gravatar_hash: "0ffdfa5b2f07204093bb08825f2ec9f1.png"

# Build settings
markdown: kramdown
exclude: [vendor]
gems: [jekyll-paginate]
analytics_id: "UA-12946032-1"

paginate: 4
paginate_path: "/blog-page-:num/"
# Gems
gems:
  - jekyll-paginate
#  - jekyll-gist
